### ISSUE TITLE
/nulis gak work

### ISSUE THREAD

**Issue by adbntgs1** [elianiva/img-to-sticker-bot#1]
KOK pas gua tes bot /nulis gak work ya,malah ngirim kertas kosong kenapa itu?

**Comment by elianiva** [comment]
- pastiin udah install imagemagick
- pastiin udah install font yg namanya `Indie Flower`

**Comment by Kochengg** [comment]
> - pastiin udah install imagemagick
> - pastiin udah install font yg namanya `Indie Flower`

`spawn is not a function`

**Comment by lvstr** [comment]
> > * pastiin udah install imagemagick
> > * pastiin udah install font yg namanya `Indie Flower`
> 
> `spawn is not a function`

gajadi deng, ane lupa syntax es6 doang ternyata hwhwhw

**Comment by elianiva** [comment]
> > > * pastiin udah install imagemagick
> > > * pastiin udah install font yg namanya `Indie Flower`
> > 
> > 
> > `spawn is not a function`
> 
> gajadi deng, ane lupa syntax es6 doang ternyata hwhwhw

siip

**Comment by lvstr** [comment]
> > > > * pastiin udah install imagemagick
> > > > * pastiin udah install font yg namanya `Indie Flower`
> > > 
> > > 
> > > `spawn is not a function`
> > 
> > 
> > gajadi deng, ane lupa syntax es6 doang ternyata hwhwhw
> 
> siip

cara install fontnya gmna gan? yg di vps, bukan localhost

**Comment by lvstr** [comment]
> > > > > * pastiin udah install imagemagick
> > > > > * pastiin udah install font yg namanya `Indie Flower`
> > > > 
> > > > 
> > > > `spawn is not a function`
> > > 
> > > 
> > > gajadi deng, ane lupa syntax es6 doang ternyata hwhwhw
> > 
> > 
> > siip
> 
> cara install fontnya gmna gan? yg di vps, bukan localhost

gajadi lagi, udh bisa akwoakwoakw

**Comment by Johanes123** [comment]
Bang, cara install imagemagicks nya gimana ya?

**Comment by elianiva** [comment]
> Bang, cara install imagemagicks nya gimana ya?

https://imagemagick.org/script/download.php

**Comment by Johanes123** [comment]
> > Bang, cara install imagemagicks nya gimana ya?
> 
> https://imagemagick.org/script/download.php

Itu yang di download http atau ftp

**Comment by elianiva** [comment]
> > > Bang, cara install imagemagicks nya gimana ya?
> > 
> > 
> > https://imagemagick.org/script/download.php
> 
> Itu yang di download http atau ftp

http
