### ISSUE TITLE
Fitur nulis

### ISSUE THREAD

**Issue by lvstr** [elianiva/img-to-sticker-bot#2]
Fitur nulis kok sendImage nya lama kali dah, sejam bahkan bisa kgk ke send

**Comment by elianiva** [comment]
bisa kasih cara buat reproduce? selama aku pake ga pernah ada masalah kaya
gini

**Comment by lvstr** [comment]
> bisa kasih cara buat reproduce? selama aku pake ga pernah ada masalah kaya
> gini
> 

Sama kea code ente, bedanya ane pake case, trus regexnya diganti dikit, hasilnya di console.log sama juga, tulisannya "done", tapi imagenya kgk ke send, ane coba di 2 akun yg beda, sama aja

**Comment by elianiva** [comment]
kurang argument terakhir buat function `client.sendImage()`
dia itu nerima 4 argument yg wajib. tujuan, file, filename, sama caption
nah kode diatas tadi ga punya argument terakhir, makanya ga kekirim fotonya

**Comment by lvstr** [comment]
> kurang argument terakhir buat function `client.sendImage()`
> dia itu nerima 4 argument yg wajib. tujuan, file, filename, sama caption
> nah kode diatas tadi ga punya argument terakhir (caption), makanya ga kekirim fotonya
> 

Itu ane edit, sebelumnya codenya sama persis, sebenernya itu imagenya ke send, cuma lama aja kesendnya, bisa ampe berjam jam baru ke send, sedangkan fitur lain bisa langsung, klo arg caption sih ane sering ga pake klo buat `sendImage()` dan hasilnya work lancar, tapi ntah knp yg satu ini ke sendnya lama kali wkwk, padahal VPSnya bisa dibilang udh mumpuni banget, trus sinyal juga strength

**Comment by elianiva** [comment]
hmmm, entah kenapa kalo gitu
soalnya di aku lancar ga ada masalah
tunggu yg lain aja deh, mungkin ada yg bisa bantu

**Comment by lvstr** [comment]
> hmmm, entah kenapa kalo gitu
> soalnya di aku lancar ga ada masalah
> tunggu yg lain aja deh, mungkin ada yg bisa bantu

Nah, sekarang baru ane coba tiba tiba cepet lagi, tapi sebelum magrib, lambat kali, aneh dah hwhwhw

**Comment by elianiva** [comment]
siip dah kalo gitu

**Comment by jsmnkk** [comment]
> > > bisa kasih cara buat reproduce? selama aku pake ga pernah ada masalah kaya
> > > gini
> > > 
> > 
> > Sama kea code ente, bedanya ane pake case, trus regexnya diganti dikit, hasilnya di console.log sama juga, tulisannya "done", tapi imagenya kgk ke send, ane coba di 2 akun yg beda, sama aja
> 
> ```
> const spawn = require("child_process");
> 
>  case "nulis":
>       console.log("writing...");
>       client.reply(from, "Sedang menulis....", id);
>       const text = message.body.replace(/\#nulis/, "");
>       const split = text.replace(/(\S+\s*){1,17}/g, "$&\n");
>       const fixedHeight = split.split("\n").slice(0, 25).join("\\n");
>       console.log(split);
>       spawn
>         .spawn("convert", [
>           "./assets/paper.jpg",
>           "-font",
>           "./assets/IndieFlower-Regular.ttf",
>           "-size",
>           "720x961",
>           "-pointsize",
>           "18",
>           "-interline-spacing",
>           "3",
>           "-annotate",
>           "+170+322",
>           fixedHeight,
>           "./assets/result.jpg",
>         ])
>         .on("error", () => console.log("error"))
>         .on("exit", () => {
>           client.sendImage(from, "./assets/result.jpg", "result.jpg");
>           console.log("done");
>         });
>       break;

Ini untuk nodejs kah bang?

**Comment by lvstr** [comment]
> > > > bisa kasih cara buat reproduce? selama aku pake ga pernah ada masalah kaya
> > > > gini
> > > > 
> > > 
> > > Sama kea code ente, bedanya ane pake case, trus regexnya diganti dikit, hasilnya di console.log sama juga, tulisannya "done", tapi imagenya kgk ke send, ane coba di 2 akun yg beda, sama aja
> > 
> > ```
> > const spawn = require("child_process");
> > 
> >  case "nulis":
> >       console.log("writing...");
> >       client.reply(from, "Sedang menulis....", id);
> >       const text = message.body.replace(/\#nulis/, "");
> >       const split = text.replace(/(\S+\s*){1,17}/g, "$&\n");
> >       const fixedHeight = split.split("\n").slice(0, 25).join("\\n");
> >       console.log(split);
> >       spawn
> >         .spawn("convert", [
> >           "./assets/paper.jpg",
> >           "-font",
> >           "./assets/IndieFlower-Regular.ttf",
> >           "-size",
> >           "720x961",
> >           "-pointsize",
> >           "18",
> >           "-interline-spacing",
> >           "3",
> >           "-annotate",
> >           "+170+322",
> >           fixedHeight,
> >           "./assets/result.jpg",
> >         ])
> >         .on("error", () => console.log("error"))
> >         .on("exit", () => {
> >           client.sendImage(from, "./assets/result.jpg", "result.jpg");
> >           console.log("done");
> >         });
> >       break;
> 
> Ini untuk nodejs kah bang?

Iya, tapi klo pake node js baru, keknya wajib pake promise, jadi ake child-process-promise, jan child_process
