### ISSUE TITLE
Bantuin fitur nulis nya dong bang

### ISSUE THREAD

**Issue by Johanes123** [elianiva/img-to-sticker-bot#3]
Pada saat saya jalan kan, yang keluar hanya gambar kertas dan tidak ada tulisan

**Comment by elianiva** [comment]
- pastiin udah keinstall imagemagick
- pastiin udah install font Indie Flower, kalo gamau tinggal ganti nama fontnya

**Comment by Bintang73** [comment]
Cara install imagemagic dan font indie flower itu gimana ya?
