### ISSUE TITLE
 imagemagick

### ISSUE THREAD

**Issue by alxxf** [elianiva/img-to-sticker-bot#4]
Abis download imagemagick terus diapain bg ???

**Comment by elianiva** [comment]
https://github.com/elianiva/img-to-sticker-bot/issues/1#issuecomment-691604809

**Comment by alxxf** [comment]
> [#1 (comment)](https://github.com/elianiva/img-to-sticker-bot/issues/1#issuecomment-691604809)

udah download font, terus download imagemagick, masih ada settingan lain gk bg ?? kok tetep gk muncul ??

**Comment by elianiva** [comment]
gaada settingan lagi harusnya, pake windows? kalo iya aku kurang bisa bantu, ga punya windows buat nyobain soalnya

**Comment by Johanes123** [comment]
> > [#1 (comment)](https://github.com/elianiva/img-to-sticker-bot/issues/1#issuecomment-691604809)
> 
> udah download font, terus download imagemagick, masih ada settingan lain gk bg ?? kok tetep gk muncul ??

-Download font terus klik kanan dan install
-download imagemagick pilih yang http terus install

Gw work kok untuk windows juga
